// File generated by FlutterFire CLI; trimmed to android + web only.
// If you run `flutterfire configure` again, restore this layout or re-trim.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Flutter application.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Resident app Firebase is configured for android and web only. '
          'Run flutterfire configure with more platforms if you add them.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5tSDonVowoBlwHLAQYeF0U_titaUIeiM',
    appId: '1:1024271924462:web:25e6d432b6e6fef9c007ff',
    messagingSenderId: '1024271924462',
    projectId: 'hydroalert-dev',
    authDomain: 'hydroalert-dev.firebaseapp.com',
    storageBucket: 'hydroalert-dev.firebasestorage.app',
    measurementId: 'G-GYYYNSPDFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbpGwfdLENxcq_RvsHWrLYt_7lGv5-58',
    appId: '1:1024271924462:android:d072237051caec04c007ff',
    messagingSenderId: '1024271924462',
    projectId: 'hydroalert-dev',
    storageBucket: 'hydroalert-dev.firebasestorage.app',
  );
}
